### Recuperar todas las peliculas
GET http://localhost:1234/movies

### Recuperar una pelicula por id
//GET http://localhost:1234/movies/:id
GET http://localhost:1234/movies/04986507-b3ed-442c-8ae7-4c5df804f896

### Recuperar todas las peliculas por un genero 
GET http://localhost:1234/movies?genre=action

### Crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "Better call Saul",
    "year": 2020,
    "director": "Saul Good Man",
    "duration": 143,
    "poster": "https://img.fruugo.com/product/7/41/14532417_max.jpg",
    "genre": ["True", "Crime"]
}


### Crear una pelicula bad request
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "Better call Saul",
    "year": 2020,
    "director": "Saul Good Man"
}

# No podremos cambiar el id porque en la validacion de los campos que hacemos el id no esta por lo tanto lo ignora
### Actualizar una pelicula
PATCH http://localhost:1234/movies/6a360a18-c645-4b47-9a7b-2a71babbf3e0
Content-Type: application/json

{
    "year":2021,
    "title": "Avatar 2",
    "id": "Cualquiera"
}